### ISSUE TITLE
 The rendering fails through the URL sharing option when they have the same name of nodes. 

### ISSUE THREAD

**Issue by yuuur** [blitzboard/blitzboard#37]
The rendering fails through the URL sharing option when they have the same name of nodes. 
If we use the same name (ID) of the node twice, the first one overwritten and the latest node rendered. 

The problem of rendering happens when sharing the URL of a graph that does not contains unique nodes. 

```
A :person prop:1
A :person prop:2
```

**Comment by ryotayamanaka** [comment]
Error messages should be shown for PG data issues.

Another PG data issue happens when the src and/or dst node are not yet defined when edges are created:

```
A
A -> B
```
