### ISSUE TITLE
JSON syntax error when node label name contains "-"

### ISSUE THREAD

**Issue by yuuur** [blitzboard/blitzboard#50]
![image](https://user-images.githubusercontent.com/74803050/135387454-6fac76bf-68b4-4914-9337-0433a505264f.png)

**Comment by ryotayamanaka** [comment]
We confirmed that this is not a bug, but a valid syntax error. The node labels should be surrounded by quotes in config:

```
'person-sus': 'f41a',
```

The default config should follow this rule (even when they do not contain `-`).

**Comment by ryotayamanaka** [comment]
Now the default config does not contain the icon entry. The future examples should use `''` appropriately.
