### ISSUE TITLE
Zip export/import option - Board names are not transferred

### ISSUE THREAD

**Issue by ryotayamanaka** [blitzboard/blitzboard#73]
The behavior after the zip import is unusual, so this should be assumed to be a bug.

**Comment by ryotayamanaka** [comment]
Now the board names are transferred, but an existing board is overwritten when a new one is imported.

**Comment by shota-matsumoto-lm** [comment]
Thank you for your reporting, I fixed it on the following commit:
https://github.com/blitzboard/blitzboard/commit/2341ff34fdbc6ea601d7f13907920796a74e842e

**Comment by ryotayamanaka** [comment]
Confirmed. Thanks!
