### ISSUE TITLE
Change the default edge width

### ISSUE THREAD

**Issue by ryotayamanaka** [blitzboard/blitzboard#80]
`width:2` seems good.

**Comment by lodenrogue** [comment]
I'm looking through the code but edge doesn't seem to have a width property. I'm looking at Blitzboard.defaultConfig

**Comment by lodenrogue** [comment]
I can add width: 2 to the default config then

**Comment by lodenrogue** [comment]
PR: https://github.com/blitzboard/blitzboard/pull/81
