### ISSUE TITLE
Need config syntax to set a default icon

### ISSUE THREAD

**Issue by ryotayamanaka** [blitzboard/blitzboard#92]
- Apply the same icon to all nodes (with any labels as, far as icons are not set for the labels)

**Comment by ryotayamanaka** [comment]
```
    icon: {
      _default: "akar-icons:person",
    },
```

**Comment by ryotayamanaka** [comment]
`_default` is added only for icon (not for other items such as size) so far.

**Comment by yutsuko24** [comment]
https://docs.blitzboard.io/visualization/nodes#node-icon
